language: r
cache: packages
sudo: false

os:
  - linux
  - osx

bioc_packages:
  - graph
  - Rgraphviz

r_github_packages:
  - jimhester/covr

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then echo 'covr::coveralls(quiet=FALSE)' | R --vanilla; fi
